// flow-typed signature: e2a806385c2817eaf5b6c80a735f2d55
// flow-typed version: <<STUB>>/canvas-confetti_v^1.4.0/flow_v0.162.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canvas-confetti'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canvas-confetti' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canvas-confetti/dist/confetti.browser' {
  declare module.exports: any;
}

declare module 'canvas-confetti/src/confetti' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canvas-confetti/dist/confetti.browser.js' {
  declare module.exports: $Exports<'canvas-confetti/dist/confetti.browser'>;
}
declare module 'canvas-confetti/src/confetti.js' {
  declare module.exports: $Exports<'canvas-confetti/src/confetti'>;
}
